/**
 * アクセス制御サービス - モックデータ
 * 共通DB構築前の開発・テスト用
 *
 * 環境変数 USE_MOCK_ACCESS_CONTROL=true で有効化
 * DB構築後は環境変数を false にするだけで本番モードに切り替え
 */

import { AccessControlConfig, AccessControlChangeLog } from './accessControlService';

/**
 * モックアクセス制御設定（17タブ）
 */
export const MOCK_ACCESS_CONTROL_CONFIGS: AccessControlConfig[] = [
  // === 基本情報カテゴリ（Level 14以上）===
  {
    id: 1,
    resourceType: 'tab',
    resourceId: 'basic',
    resourceName: '基本情報',
    category: '基本情報',
    minLevel: 14.0,
    specialAuthority: false,
    requiresAssignment: false,
    description: '職員の基本情報（氏名、所属、連絡先等）。面談業務に必須。',
    isActive: true,
    isSystemProtected: false,
    displayOrder: 1,
    recommendedMinLevel: 14.0,
    recommendedReason: '面談予約窓口（Level 14）の業務に必要な基本情報',
    createdAt: new Date('2025-10-06'),
    createdBy: 'SYSTEM',
    updatedAt: new Date('2025-10-06'),
    updatedBy: null,
  },
  {
    id: 2,
    resourceType: 'tab',
    resourceId: 'career',
    resourceName: '経歴・キャリア',
    category: '基本情報',
    minLevel: 14.0,
    specialAuthority: false,
    requiresAssignment: false,
    description: '職歴・学歴・資格取得履歴。面談時の背景理解に必要。',
    isActive: true,
    isSystemProtected: false,
    displayOrder: 2,
    recommendedMinLevel: 14.0,
    recommendedReason: '面談準備に必要なキャリア情報',
    createdAt: new Date('2025-10-06'),
    createdBy: 'SYSTEM',
    updatedAt: new Date('2025-10-06'),
    updatedBy: null,
  },
  {
    id: 3,
    resourceType: 'tab',
    resourceId: 'career-course',
    resourceName: 'キャリア選択コース',
    category: '基本情報',
    minLevel: 14.0,
    specialAuthority: false,
    requiresAssignment: false,
    description: '選択したキャリアコース（スペシャリスト/ジェネラリスト等）。',
    isActive: true,
    isSystemProtected: false,
    displayOrder: 3,
    recommendedMinLevel: 14.0,
    recommendedReason: 'キャリア支援に必要な情報',
    createdAt: new Date('2025-10-06'),
    createdBy: 'SYSTEM',
    updatedAt: new Date('2025-10-06'),
    updatedBy: null,
  },
  {
    id: 4,
    resourceType: 'tab',
    resourceId: 'mindset',
    resourceName: 'マインド・志向性',
    category: '基本情報',
    minLevel: 14.0,
    specialAuthority: false,
    requiresAssignment: false,
    description: 'モチベーションタイプ、価値観、働き方の志向性。',
    isActive: true,
    isSystemProtected: false,
    displayOrder: 4,
    recommendedMinLevel: 14.0,
    recommendedReason: '面談時の個人特性理解に必要',
    createdAt: new Date('2025-10-06'),
    createdBy: 'SYSTEM',
    updatedAt: new Date('2025-10-06'),
    updatedBy: null,
  },

  // === 資格・実績カテゴリ ===
  {
    id: 5,
    resourceType: 'tab',
    resourceId: 'qualification',
    resourceName: '資格・専門性',
    category: '資格・実績',
    minLevel: 14.0,
    specialAuthority: false,
    requiresAssignment: false,
    description: '保有資格、専門スキル、認定資格の一覧。',
    isActive: true,
    isSystemProtected: false,
    displayOrder: 5,
    recommendedMinLevel: 14.0,
    recommendedReason: '基本的な資格情報は面談で確認が必要',
    createdAt: new Date('2025-10-06'),
    createdBy: 'SYSTEM',
    updatedAt: new Date('2025-10-06'),
    updatedBy: null,
  },
  {
    id: 6,
    resourceType: 'tab',
    resourceId: 'achievement',
    resourceName: '実績・表彰',
    category: '資格・実績',
    minLevel: 15.0,
    specialAuthority: false,
    requiresAssignment: false,
    description: '業務実績、表彰歴、プロジェクト参加履歴。人事評価と連動。',
    isActive: true,
    isSystemProtected: false,
    displayOrder: 6,
    recommendedMinLevel: 15.0,
    recommendedReason: '評価に関わる実績情報は部門長以上が管理',
    createdAt: new Date('2025-10-06'),
    createdBy: 'SYSTEM',
    updatedAt: new Date('2025-10-06'),
    updatedBy: null,
  },

  // === 健康管理カテゴリ ===
  {
    id: 7,
    resourceType: 'tab',
    resourceId: 'attendance',
    resourceName: '勤務状況',
    category: '健康管理',
    minLevel: 14.0,
    specialAuthority: false,
    requiresAssignment: false,
    description: '出勤状況、勤怠記録、残業時間。面談時に確認が必要。',
    isActive: true,
    isSystemProtected: false,
    displayOrder: 7,
    recommendedMinLevel: 14.0,
    recommendedReason: '勤怠状況は面談準備に必要な情報',
    createdAt: new Date('2025-10-06'),
    createdBy: 'SYSTEM',
    updatedAt: new Date('2025-10-06'),
    updatedBy: null,
  },
  {
    id: 8,
    resourceType: 'tab',
    resourceId: 'wellbeing',
    resourceName: 'ウェルビーイング',
    category: '健康管理',
    minLevel: 97.0,
    specialAuthority: true,
    requiresAssignment: false,
    description: 'ストレスチェック結果、メンタルヘルス指標。要配慮個人情報。',
    isActive: true,
    isSystemProtected: true,
    displayOrder: 8,
    recommendedMinLevel: 97.0,
    recommendedReason: '個人情報保護法：要配慮個人情報。健診担当者・産業医のみアクセス可。',
    createdAt: new Date('2025-10-06'),
    createdBy: 'SYSTEM',
    updatedAt: new Date('2025-10-06'),
    updatedBy: null,
  },
  {
    id: 9,
    resourceType: 'tab',
    resourceId: 'health-checkup',
    resourceName: '健康診断',
    category: '健康管理',
    minLevel: 97.0,
    specialAuthority: true,
    requiresAssignment: false,
    description: '健康診断結果、再検査記録、産業医面談記録。要配慮個人情報。',
    isActive: true,
    isSystemProtected: true,
    displayOrder: 9,
    recommendedMinLevel: 97.0,
    recommendedReason: '労働安全衛生法：健康診断結果は産業医・健診担当者のみが取り扱う。',
    createdAt: new Date('2025-10-06'),
    createdBy: 'SYSTEM',
    updatedAt: new Date('2025-10-06'),
    updatedBy: null,
  },

  // === 育成・評価カテゴリ ===
  {
    id: 10,
    resourceType: 'tab',
    resourceId: 'development',
    resourceName: '能力開発',
    category: '育成・評価',
    minLevel: 15.0,
    specialAuthority: false,
    requiresAssignment: false,
    description: '研修受講履歴、スキル開発計画、OJT記録。',
    isActive: true,
    isSystemProtected: false,
    displayOrder: 10,
    recommendedMinLevel: 15.0,
    recommendedReason: '育成計画は部門長以上が管理',
    createdAt: new Date('2025-10-06'),
    createdBy: 'SYSTEM',
    updatedAt: new Date('2025-10-06'),
    updatedBy: null,
  },
  {
    id: 11,
    resourceType: 'tab',
    resourceId: 'interview',
    resourceName: '面談・指導',
    category: '育成・評価',
    minLevel: 14.0,
    specialAuthority: false,
    requiresAssignment: true,
    description: '面談記録、指導履歴、フィードバック。担当者のみ閲覧可能。',
    isActive: true,
    isSystemProtected: false,
    displayOrder: 11,
    recommendedMinLevel: 14.0,
    recommendedReason: '面談担当者は記録作成・閲覧が必要',
    createdAt: new Date('2025-10-06'),
    createdBy: 'SYSTEM',
    updatedAt: new Date('2025-10-06'),
    updatedBy: null,
  },
  {
    id: 12,
    resourceType: 'tab',
    resourceId: 'evaluation',
    resourceName: '最新評価',
    category: '育成・評価',
    minLevel: 15.0,
    specialAuthority: false,
    requiresAssignment: false,
    description: '最新の人事評価結果、評価コメント。',
    isActive: true,
    isSystemProtected: false,
    displayOrder: 12,
    recommendedMinLevel: 15.0,
    recommendedReason: '人事評価結果は部門長以上が管理',
    createdAt: new Date('2025-10-06'),
    createdBy: 'SYSTEM',
    updatedAt: new Date('2025-10-06'),
    updatedBy: null,
  },
  {
    id: 13,
    resourceType: 'tab',
    resourceId: 'evaluation-history',
    resourceName: '評価履歴',
    category: '育成・評価',
    minLevel: 15.0,
    specialAuthority: false,
    requiresAssignment: false,
    description: '過去の評価履歴、評価推移グラフ、長期トレンド分析。',
    isActive: true,
    isSystemProtected: false,
    displayOrder: 13,
    recommendedMinLevel: 15.0,
    recommendedReason: '評価履歴の分析は部門長以上の権限',
    createdAt: new Date('2025-10-06'),
    createdBy: 'SYSTEM',
    updatedAt: new Date('2025-10-06'),
    updatedBy: null,
  },
  {
    id: 14,
    resourceType: 'tab',
    resourceId: 'evaluation-report',
    resourceName: '評価分析',
    category: '育成・評価',
    minLevel: 15.0,
    specialAuthority: false,
    requiresAssignment: false,
    description: '評価の詳細分析レポート、強み・弱み分析。',
    isActive: true,
    isSystemProtected: false,
    displayOrder: 14,
    recommendedMinLevel: 15.0,
    recommendedReason: '評価分析は部門長以上がキャリア支援に活用',
    createdAt: new Date('2025-10-06'),
    createdBy: 'SYSTEM',
    updatedAt: new Date('2025-10-06'),
    updatedBy: null,
  },
  {
    id: 15,
    resourceType: 'tab',
    resourceId: 'analytics',
    resourceName: '総合分析',
    category: '育成・評価',
    minLevel: 15.0,
    specialAuthority: false,
    requiresAssignment: false,
    description: '能力開発・評価・研修の統合分析。',
    isActive: true,
    isSystemProtected: false,
    displayOrder: 15,
    recommendedMinLevel: 15.0,
    recommendedReason: '総合的な人材分析は部門長以上の権限',
    createdAt: new Date('2025-10-06'),
    createdBy: 'SYSTEM',
    updatedAt: new Date('2025-10-06'),
    updatedBy: null,
  },

  // === 採用・研修カテゴリ（Level 14以上）===
  {
    id: 16,
    resourceType: 'tab',
    resourceId: 'recruitment',
    resourceName: '採用・配属',
    category: '採用・研修',
    minLevel: 14.0,
    specialAuthority: false,
    requiresAssignment: false,
    description: '採用経緯、配属履歴、異動記録。',
    isActive: true,
    isSystemProtected: false,
    displayOrder: 16,
    recommendedMinLevel: 14.0,
    recommendedReason: '採用・配属情報は人事業務に必要',
    createdAt: new Date('2025-10-06'),
    createdBy: 'SYSTEM',
    updatedAt: new Date('2025-10-06'),
    updatedBy: null,
  },
  {
    id: 17,
    resourceType: 'tab',
    resourceId: 'education',
    resourceName: '教育・研修',
    category: '採用・研修',
    minLevel: 14.0,
    specialAuthority: false,
    requiresAssignment: false,
    description: '研修受講履歴、資格取得支援、外部研修参加記録。',
    isActive: true,
    isSystemProtected: false,
    displayOrder: 17,
    recommendedMinLevel: 14.0,
    recommendedReason: '研修管理は人事部門の基本業務',
    createdAt: new Date('2025-10-06'),
    createdBy: 'SYSTEM',
    updatedAt: new Date('2025-10-06'),
    updatedBy: null,
  },

  // === 統合管理カテゴリ（Level 14以上）===
  {
    id: 18,
    resourceType: 'tab',
    resourceId: 'links',
    resourceName: '統合管理リンク',
    category: '統合管理',
    minLevel: 14.0,
    specialAuthority: false,
    requiresAssignment: false,
    description: '他システムへのリンク、VoiceDrive連携等。',
    isActive: true,
    isSystemProtected: false,
    displayOrder: 18,
    recommendedMinLevel: 14.0,
    recommendedReason: '統合管理機能へのアクセス',
    createdAt: new Date('2025-10-06'),
    createdBy: 'SYSTEM',
    updatedAt: new Date('2025-10-06'),
    updatedBy: null,
  },
];

/**
 * モック変更履歴（サンプル）
 */
export const MOCK_CHANGE_LOG: AccessControlChangeLog[] = [
  {
    id: 1,
    masterRecordId: 12,
    resourceType: 'tab',
    resourceId: 'evaluation',
    resourceName: '最新評価',
    fieldName: 'min_level',
    oldValue: '14.0',
    newValue: '15.0',
    changeReason: 'Level 14が増加したため、評価情報は部門長以上に限定',
    isDeviationFromRecommended: false,
    changedAt: new Date('2025-10-06T10:00:00Z'),
    changedBy: 'ADMIN_001',
    changedByName: '山田太郎',
    changedByLevel: 99.0,
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0...',
  },
];
